version: 1.0.{build}
configuration: Debug

build:
  project: MusicSync.sln
  verbosity: minimal

artifacts:
- path: bin\Debug\libvideo.dll
  name: libvideo

- path: bin\Debug\NReco.VideoConverter.dll
  name: NReco.VideoConverter
