version: 1.0.{build}
configuration: Release
platform: x64

before_build:
- ps: dotnet restore

build:
  project: MusicSync.sln
  verbosity: minimal

artifacts:
- path: packages\VideoLibrary.1.3.5\*.nupkg
  name: Release